### ISSUE TITLE
Simple flexible - Illegal offset type

### ISSUE THREAD

**Issue by nlemoine** [BeAPI/bea-beautiful-flexible#10]
I get a warning here: https://github.com/BeAPI/bea-beautiful-flexible/blob/master/classes/main.php#L68

`$layout_field` is an array and can't be used as an array key. I didn't submit a PR because I didn't dig further and don't know what this condition is here to prevent. Did you mean by chance:
```php 
if ( $keys [ $layout_field['key'] ] ) {
	continue;
}
```
?

Let me know if you need more informations. 

#### Version information

* Plugin version : 1.0.3
* ACF version : 5.7.4
* PHP : 7.1
* WordPress : 4.9.8

#### Steps to reproduce

1. Create a flexible
2. Use this plugin
3. Visit any page containing the flexible field

#### What was expected

No notice or warning.

#### What happened instead

`Illegal offset type in /path/to/plugins/bea-beautiful-flexible/classes/main.php on line 69`

**Comment by MaximeCulea** [comment]
@nlemoine thank you for the issue submitting.

> Visit any page containing the flexible field

Where, in front or dashboard ?

Just to know, that was intented to prevent working on existing keys. Without debugging, I can't be sure what is the good way to fix, but 2 possibilities :
- `! empty( $keys [ $layout_field ] )`
- ` isset( $keys [ $layout_field ] )`

If you have time to debbug and make a PR, that's cool. Otherwise I'll have a look into this.
Thank you

**Comment by nlemoine** [comment]
Hello @MaximeCulea, see the PR and let me know if some changes are required.

**Comment by MaximeCulea** [comment]
@nlemoine and @dominikkucharski, this has been fixed https://github.com/BeAPI/bea-beautiful-flexible/commit/fe5542882b7a0312ef0421b7fe09280ab0610dff

FYI, it will be launched into the next release.

**Comment by nlemoine** [comment]
Great news! Thanks.

**Comment by MaximeCulea** [comment]
New release (1.0.4) just launched.

**Comment by dominikkucharski** [comment]
Unfortunately, this issue is not fixed. I still see the same error.

**Comment by MaximeCulea** [comment]
Hello @dominikkucharski, thank for the feedback. I reopen the issue.
Have you some more details to provide ?
Do you think it's the same warning ?
Thank you

**Comment by dominikkucharski** [comment]
I think it's the same warning. 

I've disabled all plugins except bea-beautiful-flexible and ACF Pro in the latest version and when I go to the screen creating a new field Groups I see this:

![zrzut ekranu 2018-10-17 o 13 08 56](https://user-images.githubusercontent.com/1243751/47082572-50192380-d20e-11e8-81ed-293bc611b91b.jpg)

I'm using PHP 7.1.2

**Comment by MaximeCulea** [comment]
@dominikkucharski Corrected into 1.0.5.
Thank you for your understanding.
